version: '3.9'

services:
    be:
        build: .
        container_name: be
        command: npm run start
        depends_on:
            - redis
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data

    email_worker:
        build: .
        container_name: email_worker
        command: node dist/workers/email.js
        depends_on:
            - redis

volumes:
    redis_data:
